services:
  postgres:
    image: postgres:16
    container_name: lanyard_postgres
    environment:
      POSTGRES_DB: LanyardDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: