name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: self-hosted  
    steps:
      - uses: actions/checkout@v4

      - name: Install Velopack CLI
        run: /home/github-runner/.dotnet/dotnet tool install -g vpk

      - name: Publish app
        run: /home/github-runner/.dotnet/dotnet publish src/LanyardClient/Lanyard.Client.csproj -c Release -r linux-x64 --self-contained -o ./publish

      - name: Package with Velopack
        run: /home/github-runner/.dotnet/dotnet vpk pack --packId LanyardClient --packVersion ${{ github.ref_name }} --packDir ./publish --mainExe LanyardClient

      - name: Upload to GitHub Releases
        run: /home/github-runner/.dotnet/dotnet vpk upload github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }} --tag ${{ github.ref_name }}